STOCKS = [
"RELIANCE","HDFCBANK","ICICIBANK","SBIN",
"AXISBANK","LT","INFY","TCS","TATASTEEL","JSWSTEEL",
"ADANIENT","ADANIPORTS","INDUSINDBK","BAJFINANCE","M&M",
"HINDALCO","COALINDIA","ONGC","POWERGRID",
"ULTRACEMCO","GRASIM","NTPC","BPCL","DIVISLAB"
]

INTERVAL = "5m"
PERIOD = "5d"